import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import Navbar from "@/app/ui/Navbar";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./ui/header";
import ServerComponent from "./ui/ServerC";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <Providers>
          {/* <Navbar /> */}
          {/* <Header/> */}
          <ServerComponent/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
